// 0x0D00001C
const GeoLayout mr_i_iris_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(20, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_open),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_mostly_open),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_mostly_closed),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_closed),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_mostly_closed),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_mostly_open),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_open),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_open),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_open),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_mostly_open),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_mostly_closed),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_closed),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_mostly_closed),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_mostly_open),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_open),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_open),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_open),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_open),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_open),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, mr_i_iris_seg6_dl_open),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
