// 0x170001BC
const GeoLayout sparkles_geo[] = {
   GEO_SWITCH_CASE(12, geo_switch_anim_state),
   GEO_OPEN_NODE(),
      GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, sparkles_seg4_dl_5),
      GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, sparkles_seg4_dl_5),
      GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, sparkles_seg4_dl_4),
      GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, sparkles_seg4_dl_4),
      GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, sparkles_seg4_dl_3),
      GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, sparkles_seg4_dl_3),
      GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, sparkles_seg4_dl_2),
      GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, sparkles_seg4_dl_2),
      GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, sparkles_seg4_dl_1),
      GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, sparkles_seg4_dl_1),
      GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, sparkles_seg4_dl_0),
      GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, sparkles_seg4_dl_0),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
