#ifdef IA8_30FPS_COINS
// 0x1600013C
const GeoLayout yellow_coin_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 50),
   GEO_OPEN_NODE(),
      GEO_RENDER_RANGE(-2048, 3072),
      GEO_OPEN_NODE(),
         GEO_SWITCH_CASE(8, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_0),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_22_5),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_45),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_67_5),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_90),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_67_5_r),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_45_r),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_22_5_r),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_RENDER_RANGE(3072, 32767),
      GEO_OPEN_NODE(),
         GEO_SWITCH_CASE(8, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_front),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_front),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_tilt_right),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_tilt_right),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_side),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_side),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_tilt_left),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_tilt_left),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x160001A0
const GeoLayout yellow_coin_no_shadow_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_RENDER_RANGE(-2048, 3072),
      GEO_OPEN_NODE(),
         GEO_SWITCH_CASE(8, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_0),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_22_5),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_45),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_67_5),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_90),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_67_5_r),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_45_r),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_22_5_r),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_RENDER_RANGE(3072, 32767),
      GEO_OPEN_NODE(),
         GEO_SWITCH_CASE(8, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_front),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_front),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_tilt_right),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_tilt_right),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_side),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_side),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_tilt_left),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_yellow_tilt_left),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000200
const GeoLayout blue_coin_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 80),
   GEO_OPEN_NODE(),
      GEO_RENDER_RANGE(-2048, 3072),
      GEO_OPEN_NODE(),
         GEO_SWITCH_CASE(8, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_0),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_22_5),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_45),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_67_5),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_90),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_67_5_r),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_45_r),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_22_5_r),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_RENDER_RANGE(3072, 32767),
      GEO_OPEN_NODE(),
         GEO_SWITCH_CASE(8, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_front),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_front),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_tilt_right),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_tilt_right),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_side),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_side),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_tilt_left),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_tilt_left),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000264
const GeoLayout blue_coin_no_shadow_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_RENDER_RANGE(-2048, 3072),
      GEO_OPEN_NODE(),
         GEO_SWITCH_CASE(8, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_0),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_22_5),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_45),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_67_5),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_90),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_67_5_r),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_45_r),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_22_5_r),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_RENDER_RANGE(3072, 32767),
      GEO_OPEN_NODE(),
         GEO_SWITCH_CASE(8, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_front),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_front),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_tilt_right),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_tilt_right),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_side),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_side),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_tilt_left),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_blue_tilt_left),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x160002C4
const GeoLayout red_coin_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 80),
   GEO_OPEN_NODE(),
      GEO_RENDER_RANGE(-2048, 3072),
      GEO_OPEN_NODE(),
         GEO_SWITCH_CASE(8, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_0),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_22_5),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_45),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_67_5),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_90),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_67_5_r),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_45_r),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_22_5_r),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_RENDER_RANGE(3072, 32767),
      GEO_OPEN_NODE(),
         GEO_SWITCH_CASE(8, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_front),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_front),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_tilt_right),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_tilt_right),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_side),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_side),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_tilt_left),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_tilt_left),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000328
const GeoLayout red_coin_no_shadow_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_RENDER_RANGE(-2048, 3072),
      GEO_OPEN_NODE(),
         GEO_SWITCH_CASE(8, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_0),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_22_5),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_45),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_67_5),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_90),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_67_5_r),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_45_r),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_22_5_r),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_RENDER_RANGE(3072, 32767),
      GEO_OPEN_NODE(),
         GEO_SWITCH_CASE(8, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_front),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_front),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_tilt_right),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_tilt_right),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_side),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_side),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_tilt_left),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_red_tilt_left),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x160002C4
const GeoLayout silver_coin_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 80),
   GEO_OPEN_NODE(),
      GEO_RENDER_RANGE(-2048, 3072),
      GEO_OPEN_NODE(),
         GEO_SWITCH_CASE(8, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_0),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_22_5),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_45),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_67_5),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_90),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_67_5_r),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_45_r),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_22_5_r),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_RENDER_RANGE(3072, 32767),
      GEO_OPEN_NODE(),
         GEO_SWITCH_CASE(8, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_front),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_front),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_tilt_right),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_tilt_right),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_side),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_side),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_tilt_left),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_tilt_left),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000328
const GeoLayout silver_coin_no_shadow_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_RENDER_RANGE(-2048, 3072),
      GEO_OPEN_NODE(),
         GEO_SWITCH_CASE(8, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_0),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_22_5),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_45),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_67_5),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_90),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_67_5_r),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_45_r),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_22_5_r),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_RENDER_RANGE(3072, 32767),
      GEO_OPEN_NODE(),
         GEO_SWITCH_CASE(8, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_front),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_front),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_tilt_right),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_tilt_right),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_side),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_side),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_tilt_left),
            GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_secret_tilt_left),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

#else
// 0x1600013C
const GeoLayout yellow_coin_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 50),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007800),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007800),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007828),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007828),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007850),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007850),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007878),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007878),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x160001A0
const GeoLayout yellow_coin_no_shadow_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007800),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007800),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007828),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007828),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007850),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007850),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007878),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007878),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000200
const GeoLayout blue_coin_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 80),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_030078A0),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_030078A0),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_030078C8),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_030078C8),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_030078F0),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_030078F0),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007918),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007918),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000264
const GeoLayout blue_coin_no_shadow_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_030078A0),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_030078A0),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_030078C8),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_030078C8),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_030078F0),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_030078F0),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007918),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007918),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x160002C4
const GeoLayout red_coin_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 80),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007940),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007940),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007968),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007968),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007990),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007990),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_030079B8),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_030079B8),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

// 0x16000328
const GeoLayout red_coin_no_shadow_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(8, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007940),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007940),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007968),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007968),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007990),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_03007990),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_030079B8),
         GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, coin_seg3_dl_030079B8),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
#endif
