// 0x0D0000DC
const GeoLayout swoop_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0x96, 100),
   GEO_OPEN_NODE(),
      GEO_SCALE(LAYER_FORCE, 16384),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 0, 0, 0, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_BILLBOARD(),
               GEO_OPEN_NODE(),
                  GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, dSwoopBodyDl),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 54, 0, 0, swoop_seg6_dl_06006758),
               GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 54, 0, 0, swoop_seg6_dl_06006A88),
               GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 57, -48, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE_ALPHA, 0, 0, 0, dSwoopWing1Dl),
               GEO_CLOSE_NODE(),
               GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 57, -48, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE_ALPHA, 0, 0, 0, dSwoopWing2Dl),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
