// 0x0D000000
const GeoLayout bowser_flames_geo[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(14, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, flame_seg6_dl_0),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, flame_seg6_dl_1),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, flame_seg6_dl_2),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, flame_seg6_dl_3),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, flame_seg6_dl_4),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, flame_seg6_dl_5),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, flame_seg6_dl_6),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, flame_seg6_dl_7),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, flame_seg6_dl_8),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, flame_seg6_dl_9),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, flame_seg6_dl_10),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, flame_seg6_dl_11),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, flame_seg6_dl_12),
         GEO_DISPLAY_LIST(LAYER_TRANSPARENT, flame_seg6_dl_13),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
