// 0x0D000000
const GeoLayout lakitu_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0x96, 100),
   GEO_OPEN_NODE(),
      GEO_SCALE(LAYER_FORCE, 16384),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 0, 0, 0, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 0, 0, 0, lakitu_seg6_dl_06003E30),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 132, 0, 0, lakitu_seg6_dl_cameraman_frown),
               GEO_OPEN_NODE(),
                  GEO_SWITCH_CASE(2, geo_switch_anim_state),
                  GEO_OPEN_NODE(),
                     GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, lakitu_seg6_dl_cameraman_eyes_open),
                     GEO_DISPLAY_LIST(LAYER_NO_SILHOUETTE_ALPHA, lakitu_seg6_dl_cameraman_eyes_closed),
                  GEO_CLOSE_NODE(),
               GEO_CLOSE_NODE(),
               GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 87, 18, 72, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 0, 0, 0, lakitu_seg6_dl_060047E8),
               GEO_CLOSE_NODE(),
               GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 87, 18, -72, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 0, 0, 0, lakitu_seg6_dl_060049E0),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 334, -214, -50, NULL),
                     GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 0, 0, 0, lakitu_seg6_dl_cameraman_black_string_2),
                        GEO_OPEN_NODE(),
                           GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 191, 0, 0, lakitu_seg6_dl_camera),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 0, 0, 0, lakitu_seg6_dl_cameraman_black_string_1),
                     GEO_CLOSE_NODE(),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_NO_SILHOUETTE, 0, 0, 0, lakitu_seg6_dl_06005598),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
